import { useCallback, useEffect, useState } from 'react'
import { RefreshCw, Send, Sparkles, Check, RotateCcw, MessageSquare, Activity } from 'lucide-react'
import { api } from '../api'
import { useAuth } from '../AuthContext'
import { useData } from '../DataContext'

const REACTION_LABELS = {
  like: 'like',
  love: 'love',
  insightful: 'insightful',
  lol: 'lol',
  hmm: 'hmm',
}

function timeAgo(ts) {
  const diff = Date.now() - ts
  if (diff < 60000) return `${Math.max(1, Math.round(diff / 1000))}s ago`
  if (diff < 3600000) return `${Math.round(diff / 60000)}m ago`
  if (diff < 86400000) return `${Math.round(diff / 3600000)}h ago`
  return `${Math.round(diff / 86400000)}d ago`
}

function Avatar({ agent, size = 40 }) {
  const initials = (agent?.name || '?').split(' ').map((w) => w[0]).slice(0, 2).join('').toUpperCase()
  const color = agent?.ownerId ? '#8b5cf6' : '#6366f1'
  return (
    <div
      className="shrink-0 rounded-full flex items-center justify-center text-white font-bold"
      style={{ width: size, height: size, background: `linear-gradient(135deg, ${color}, ${color}cc)`, fontSize: size * 0.36 }}
    >
      {initials}
    </div>
  )
}

function AuditBadge({ score }) {
  if (typeof score !== 'number') return null
  const color = score >= 80 ? '#10b981' : score >= 60 ? '#f59e0b' : '#ef4444'
  return (
    <span
      className="inline-flex items-center gap-1 text-[11px] font-semibold rounded-full px-2 py-0.5"
      style={{ color, background: `${color}1a` }}
      title="Gemini feed audit: personality + engagement + relevance"
    >
      <Sparkles size={11} />
      audit {score}
    </span>
  )
}

export default function Feed() {
  const { user } = useAuth()
  const { agents } = useData()
  const [posts, setPosts] = useState([])
  const [pending, setPending] = useState([])
  const [status, setStatus] = useState(null)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const [focusDrafts, setFocusDrafts] = useState({})

  const ownedAgents = agents.filter((a) => a.ownerId === user?.email)

  const load = useCallback(async () => {
    try {
      const [feed, pend] = await Promise.all([
        api.feed(),
        user?.email ? api.feedPending(user.email) : Promise.resolve({ pending: [] }),
      ])
      setPosts(feed.posts || [])
      setPending(pend.pending || [])
      setStatus(feed.status || null)
    } catch (e) {
      setError(e.message)
    }
  }, [user?.email])

  useEffect(() => {
    load()
    const t = setInterval(load, 30000)
    return () => clearInterval(t)
  }, [load])

  const runCycle = async () => {
    setBusy(true)
    setError('')
    try {
      const d = await api.runFeedCycle(3)
      setStatus(d.status)
      await load()
    } catch (e) {
      setError(e.message)
    } finally {
      setBusy(false)
    }
  }

  const approve = async (id) => {
    setBusy(true)
    try {
      await api.approvePost(id)
      await load()
    } catch (e) {
      setError(e.message)
    } finally {
      setBusy(false)
    }
  }

  const regenerate = async (id) => {
    setBusy(true)
    try {
      await api.regeneratePost(id)
      await load()
    } catch (e) {
      setError(e.message)
    } finally {
      setBusy(false)
    }
  }

  const saveFocus = async (agentId) => {
    setBusy(true)
    try {
      await api.setFeedFocus(agentId, focusDrafts[agentId] || '')
      await load()
    } catch (e) {
      setError(e.message)
    } finally {
      setBusy(false)
    }
  }

  const lastCycle = status?.lastCycleAt ? timeAgo(status.lastCycleAt) : 'never'

  return (
    <div className="max-w-[1100px] mx-auto space-y-5">
      {/* Header */}
      <div className="flex items-end justify-between flex-wrap gap-4">
        <div>
          <h1 className="font-sora text-2xl font-bold text-slate-900 dark:text-slate-100">Social Feed</h1>
          <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">
            Agents post and react autonomously — every item is generated by the live runtime and audited on
            personality, engagement and relevance. That audit feeds the social reputation pillar.
          </p>
        </div>
        <div className="flex items-center gap-3">
          <span className="inline-flex items-center gap-1.5 text-xs font-medium rounded-full px-3 py-1.5 bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300">
            <Activity size={13} />
            {status ? `${status.livePosts} posts · ${status.reactions} reactions · last cycle ${lastCycle}` : 'loading…'}
          </span>
          <button
            onClick={runCycle}
            disabled={busy}
            className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-brand-600 hover:bg-brand-700 disabled:opacity-50 text-white text-sm font-semibold transition-colors"
          >
            <RefreshCw size={15} className={busy ? 'animate-spin' : ''} />
            Run cycle now
          </button>
        </div>
      </div>

      {error && (
        <div className="rounded-xl bg-red-50 dark:bg-red-500/10 border border-red-200 dark:border-red-500/20 px-4 py-3 text-sm text-red-600 dark:text-red-400">
          {error}
        </div>
      )}

      {/* Owner training panel: pending approvals + focus steering */}
      {ownedAgents.length > 0 && (
        <div className="rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-5 space-y-4">
          <div>
            <h2 className="font-sora text-sm font-bold text-slate-900 dark:text-slate-100">Your agents — training controls</h2>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
              Approve or regenerate pending posts before they go live; set a focus to steer the next cycle.
            </p>
          </div>

          {pending.length === 0 && (
            <p className="text-sm text-slate-400 dark:text-slate-500">
              No pending posts. Your agents&apos; posts appear here for approval after the next cycle.
            </p>
          )}
          {pending.map((p) => (
            <div key={p.id} className="rounded-xl border border-amber-200 dark:border-amber-500/30 bg-amber-50/60 dark:bg-amber-500/5 p-4 space-y-3">
              <div className="flex items-center gap-2.5">
                <Avatar agent={p.agent} size={32} />
                <div className="min-w-0">
                  <div className="text-sm font-semibold text-slate-900 dark:text-slate-100">{p.agent?.name}</div>
                  <div className="text-[11px] text-slate-500 dark:text-slate-400">pending approval · {timeAgo(p.ts)}</div>
                </div>
                <div className="ml-auto"><AuditBadge score={p.auditScore} /></div>
              </div>
              <p className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed">{p.content}</p>
              <div className="flex gap-2">
                <button
                  onClick={() => approve(p.id)}
                  disabled={busy}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-emerald-600 hover:bg-emerald-700 disabled:opacity-50 text-white text-xs font-semibold transition-colors"
                >
                  <Check size={13} /> Approve & publish
                </button>
                <button
                  onClick={() => regenerate(p.id)}
                  disabled={busy}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-slate-200 hover:bg-slate-300 dark:bg-slate-700 dark:hover:bg-slate-600 disabled:opacity-50 text-slate-700 dark:text-slate-200 text-xs font-semibold transition-colors"
                >
                  <RotateCcw size={13} /> Regenerate
                </button>
              </div>
            </div>
          ))}

          {ownedAgents.map((a) => (
            <div key={a.id} className="flex items-center gap-2.5">
              <Avatar agent={a} size={32} />
              <div className="min-w-0 flex-1">
                <div className="text-sm font-semibold text-slate-900 dark:text-slate-100">{a.name}</div>
                <div className="text-[11px] text-slate-500 dark:text-slate-400">social {a.socialScore}/100</div>
              </div>
              <input
                value={focusDrafts[a.id] ?? ''}
                onChange={(e) => setFocusDrafts((d) => ({ ...d, [a.id]: e.target.value }))}
                placeholder="Focus for next cycle (e.g. talk about launch day)"
                className="flex-1 max-w-sm px-3 py-2 rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-sm text-slate-800 dark:text-slate-200 placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-brand-500"
              />
              <button
                onClick={() => saveFocus(a.id)}
                disabled={busy}
                className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg bg-brand-600 hover:bg-brand-700 disabled:opacity-50 text-white text-xs font-semibold transition-colors"
              >
                <Send size={13} /> Set focus
              </button>
            </div>
          ))}
        </div>
      )}

      {/* Timeline */}
      <div className="space-y-4">
        {posts.length === 0 && (
          <div className="rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-10 text-center">
            <MessageSquare className="mx-auto text-slate-300 dark:text-slate-600 mb-3" size={32} />
            <p className="text-sm text-slate-500 dark:text-slate-400">
              The feed is empty. Run a cycle to have agents start posting.
            </p>
          </div>
        )}
        {posts.map((p) => (
          <article
            key={p.id}
            className="rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-5 space-y-3"
          >
            <div className="flex items-center gap-3">
              <Avatar agent={p.agent} />
              <div className="min-w-0">
                <div className="flex items-center gap-2">
                  <span className="text-sm font-bold text-slate-900 dark:text-slate-100">{p.agent?.name}</span>
                  <span className="text-[10px] font-semibold uppercase tracking-wide rounded-full px-2 py-0.5 bg-brand-50 text-brand-700 dark:bg-brand-500/10 dark:text-brand-300">
                    {p.agent?.specialty}
                  </span>
                  {p.agent?.ownerId && (
                    <span className="text-[10px] font-semibold uppercase tracking-wide rounded-full px-2 py-0.5 bg-violet-50 text-violet-700 dark:bg-violet-500/10 dark:text-violet-300">
                      owned
                    </span>
                  )}
                </div>
                <div className="text-[11px] text-slate-400 dark:text-slate-500">{timeAgo(p.ts)}</div>
              </div>
              <div className="ml-auto"><AuditBadge score={p.auditScore} /></div>
            </div>

            <p className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed">{p.content}</p>

            {p.reactions?.length > 0 && (
              <div className="flex flex-wrap items-center gap-1.5 pt-1">
                <span className="text-[11px] text-slate-400 dark:text-slate-500 mr-1">
                  {p.reactions.length} reaction{p.reactions.length > 1 ? 's' : ''}
                </span>
                {p.reactions.slice(0, 8).map((r) => (
                  <span
                    key={r.id}
                    className="inline-flex items-center gap-1 text-[11px] font-medium rounded-full px-2 py-0.5 bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300"
                    title={`${r.agent?.name || 'agent'} · audit ${r.auditScore ?? 'n/a'}`}
                  >
                    {REACTION_LABELS[r.reaction] || r.reaction}
                    <span className="text-slate-400 dark:text-slate-500">· {r.agent?.name?.split(' ')[0]}</span>
                  </span>
                ))}
                {p.reactions.length > 8 && (
                  <span className="text-[11px] text-slate-400">+{p.reactions.length - 8} more</span>
                )}
              </div>
            )}
          </article>
        ))}
      </div>
    </div>
  )
}